/**
 * From:
 * https://www.pantomime-popkultur.de/2010/11/pantomime-spiele-und-begriffe/
 * https://www.pantomime-popkultur.de/2016/12/pantomime-begriffe-und-woerter-listen-fuer-scharade-teil-2/
 * https://www.pantomime-popkultur.de/2020/04/pantomime-woerter-pervers/
 * https://www.desired.de/lifestyle/pantomime-begriffe/
 * https://www.praxis-jugendarbeit.de/spielesammlung/spiele-pantomime.html
 */
export const GUESS_WORDS = [
  "Fernbedienung",
  "Rasierschaum",
  "Laderampe",
  "Lichterkette",
  "Rauhfasertapete",
  "Tannenbaumständer",
  "Siebträgermaschine",
  "Lampenfassung",
  "Schneeketten",
  "Konfettiregen",
  "Geschenkpapier",
  "Wollschal",
  "Schleifenbank",
  "Rundumleuchte",
  "Kegelbahn",
  "Schaukelpferd",
  "Verhaltensmuster",
  "Handcreme",
  "Räuchermännchen",
  "Querschläger",
  "Adventskalender",
  "Brillenputztuch",
  "Hauptgewinn",
  "Wäscheklammer",
  "Spiegelreflexkamera",
  "Pralinenschachtel",
  "Drehbuch",
  "Kinderstuhl",
  "Sonnenblumenöl",
  "Christbaumkugel",
  "Zungenkuss",
  "Ladegerät",
  "Schreihals",
  "Glühwein",
  "Osterhase",
  "Teppichklopfer",
  "Schokokringel",
  "Vollpfosten",
  "Sprudelwasser",
  "Kickstarter",
  "Eierlikör",
  "Neujahresgruß",
  "Glatteis",
  "Weihnachtsgans",
  "Lebkuchenherz",
  "Trostpreis",
  "Versuchskaninchen",
  "Regalboden",
  "Mistelzweig",
  "Hebamme",
  "Manschettenknopf",
  "Schneegestöber",
  "Renntier",
  "Winterstiefel",
  "Flussufer",
  "Pfauenfeder",
  "Ohrensessel",
  "Verlobungsring",
  "Garagentür",
  "Weihnachtspost",
  "Glasreiniger",
  "Intimpiercing",
  "Gießkanne",
  "Hackebeil",
  "Tiefkühlfach",
  "Treppenhaus",
  "Fahrradschlauch",
  "Kreißsaal",
  "Mitesser",
  "Armdrücken",
  "Armleuchter",
  "Auto",
  "Aalglatt",
  "Aasgeier",
  "Altklug",
  "Aschenbecher",
  "A-loch",
  "Autotür",
  "Autoschlüssel",
  "Arschbombe",
  "Angelrute",
  "Butterdose",
  "Buchrücken",
  "Buntstift",
  "Bademeister",
  "Barhocker",
  "Besenkammer",
  "Bienenstich",
  "Blattlaus",
  "Brecheisen",
  "Bankverbindung",
  "Christkind",
  "Chinapfanne",
  "Chemielabor",
  "Druckerpatrone",
  "Dachterasse",
  "Dosenöffner",
  "Darmspülung",
  "Dübel",
  "Dönerbude",
  "Erbsenzähler",
  "Eselsbrücke",
  "Eisverkäufer",
  "Eisenbahn",
  "Elefantenhaut",
  "Elfenbeinküste",
  "Feuerwasser",
  "Feuchttücher",
  "Freudenhaus",
  "Fundgrube",
  "Fallobst",
  "Freiheitsstatue",
  "Federkissen",
  "Frauenarzt",
  "Gürteltasche",
  "Glatteis",
  "Gemüsebeet",
  "Gorilla",
  "Gummiboot",
  "Giraffe",
  "Gartenschlauch",
  "Himmelbett",
  "Hirtenstab",
  "Hängematte",
  "Haubentaucher",
  "Hufeisen",
  "Hirschgeweih",
  "Hippie",
  "Hundeleine",
  "Irrenhaus",
  "Imker",
  "Igel",
  "Internet",
  "Indianer",
  "Judo",
  "Jongleur",
  "Jagdhorn",
  "Joghurtbecher",
  "Kuh",
  "Kettenkarussell",
  "Kautabak",
  "Kerzendocht",
  "Klaviertaste",
  "Käseglocke",
  "Kuchengabel",
  "Lochfraß",
  "Lichterkette",
  "Lesezeichen",
  "Luftmatratze",
  "Luftballon",
  "Motorroller",
  "Matrosenmütze",
  "Münzautomat",
  "Menschenaffe",
  "Mondschein",
  "Magnet",
  "Müllbeutel",
  "Nasenbär",
  "Navigationssystem",
  "Nussschale",
  "Naschkatze",
  "Nähmaschine",
  "Osterhaase",
  "Ofenrohr",
  "Obstmesser",
  "Orgelpfeife",
  "Obstkorb",
  "Patronengürtel",
  "Pfandflasche",
  "Polizeiauto",
  "Portemonnaie",
  "Plattenspieler",
  "Quadratzentimeter",
  "Qualle",
  "Querflöte",
  "Raubüberfall",
  "Rollator",
  "Rübe",
  "Rosengarten",
  "Rundumleuchte",
  "Reisewecker",
  "Schlüsselloch",
  "Statue",
  "Schachbrett",
  "Schnürsenkel",
  "Seifenspender",
  "Schreibtischlampe",
  "Stehaufmännchen",
  "Suppenkasper",
  "Skilift",
  "Sandkasten",
  "Türklinke",
  "Tattoonadel",
  "Teebeutel",
  "Triathlon",
  "Tortenheber",
  "U-Boot",
  "Umhang",
  "Überwachungskamera",
  "USB-Kabel",
  "Vogelnest",
  "Vorhang",
  "Verkehrspolizist",
  "Waffeleisen",
  "Wandregal",
  "Waschbecken",
  "Wasserball",
  "Wasserwaage",
  "Yoga",
  "Zahnfee",
  "Zigaretten",
  "Zahnarzt",
  "Zitronenbaum",
  "Zimmerpflanze",
  "Zungenkuss",
  "Zielscheibe",
  "Poledance",
  "Skispringer",
  "Wildschwein",
  "Blähungen",
  "Schaukelpferd",
  "Baby",
  "Glatteis",
  "Zombie",
  "Vibrator",
  "Domina",
  "Stripper",
  "Brillenschlange",
  "Klapperschlange",
  "Federhalter",
  "Luftschloss",
  "Flohzirkus",
  "Durchfall",
  "Gasthof",
  "Bankraub",
  "Briefwaage",
  "Aschenbecher",
  "Spiegelbild",
  "Spielleiter",
  "Hausschuhe",
  "Stierkampf",
  "Waldhornbläser",
  "Tischtennisball",
  "Schallplattenspieler",
  "Weinberg",
  "Löwenzahn",
  "Bauchladen",
  "Schriftsteller",
  "Buchhändler",
  "Schneemann",
  "Kindergarten",
  "Trinkgeld",
  "Der König der Löwen",
  "Der Herr der Ringe",
  "Harry Potter",
  "Das letzte Einhorn",
  "Die Schöne und das Biest",
  "Das Dschungelbuch",
  "Oben",
  "Der Glöckner von Notre Dame",
  "Die Simpsons",
  "Asterix & Obelix",
  "Mary Poppins",
  "Pinoccio",
  "Pippi Langstrumpf",
  "Die fantastische Welt von Oz",
  "Titanic",
  "Der Teufel trägt Prada",
  "Fabelhafte Welt der Amelie",
  "Ghostbusters",
  "Bridget Jones – Schokolade zum Frühstück",
  "Batman",
  "Shrek",
  "Pulp Fiction",
  "Toy Story",
  "The Matrix",
  "Kevin allein zu Haus",
  "Inception",
  "Twilight",
  "50 Shades of Grey",
  "Charlie und die Schokoladenfabrik",
  "Romeo und Julia",
  "Ironman",
  "Captian America",
  "Hulk",
  "Avengers",
  "Poledance",
  "Skispringer",
  "Blähungen",
  "Schaukelpferd",
  "Seekuh",
  "Baby ",
  "Glatteis",
  "Zombie",
  "melken (Kuh) ",
  "Fusspilz",
  "Wildschwein",
  "ausziehen",
  "Marathon",
  "Fetisch",
  "Buddhismus",
  "9-11 (11. September)",
  "Feinstaub",
  "Groupies",
  "Vorschau",
  "Fremdscham",
  "Kanibalismus",
  "Monobraue",
  "Hausarrest",
  "Groupies",
  "Asyl",
  "Schlussstrich",
  "Osterhase",
  "Hexe",
  "kopieren",
  "Drehtür",
  "Waffeleisen",
  "Glühwein",
  "Nassrasur",
  "Schnittlauch",
  "Kettenkarrussell",
  "Kellerassel",
  "Sesselpupser",
  "Sparschwein",
  "Büchsenöffner",
  "Teelöffel",
  "Vermögensberater",
  "Mehl",
  "Klodeckel",
  "Tandem (Fahrrad)",
  "Ehebett",
  "Nachttischlampe",
  "Zärtlichkeiten",
  "Hämorrhoiden",
  "Weltenbummler",
  "Domina",
  "One Night Stand",
  "Strippen/ Stripper",
  "Orgie",
  "Kondom",
  "Blowjob",
  "Zungenkuss",
  "Busensex",
  "SM-Spiele",
  "Vibrator ",
  "Intimrasur ",
  "69er-Stellung",
  "Analsex",
  "Besetzungscouch",
  "Milf",
  "Fußerotik",
  "Missionarsstellung",
  "Kamasutra",
  "Achselschweiß",
  "Affentheater",
  "aufstehen",
  "Autoreparatur",
  "Bär",
  "betrunken",
  "Biene Maja",
  "Bierfaß",
  "Blaumeise",
  "Bleifuß",
  "Brustschwimmen",
  "Burgturm",
  "Burgfräulein",
  "Clown",
  "Tisch decken",
  "Detektiv",
  "Dickkopf",
  "Dirigent",
  "Dompteur",
  "Dornröschen",
  "Drehwurm",
  "Bild malen",
  "Nähen",
  "Kuchen backen",
  "Pistolenduell",
  "Angeln",
  "Eisbär",
  "Elefant",
  "Elefantenwäsche ",
  "Elvis",
  "Kochen",
  "Fahrrad fahren",
  "Federball spielen",
  "Federhalter",
  "Fee",
  "Fernseher",
  "Flaschenhals",
  "Fliegenfänger",
  "Flügelschlag",
  "Folterkammer",
  "Fotomodell",
  "Friseur",
  "fröhlich",
  "Frosch",
  "Fußball",
  "Fußpilz",
  "Gabelstapler",
  "gelangweilt",
  "Gitarre",
  "Großeltern",
  "Handschuh",
  "Handstock",
  "Haarföhn",
  "Herzensbrecher",
  "Hosenträger",
  "Kino",
  "Museum",
  "Joggen",
  "Kaffee kochen",
  "Kameltreiber",
  "Känguru",
  "Karten spielen",
  "Käsefüße",
  "Kellnerin",
  "Kettenraucher",
  "Klavier",
  "Klobrille",
  "Kniebank",
  "Knopf",
  "Kopfschmerzen",
  "Kreissäge",
  "Kuhglocke",
  "Lachsack",
  "Lehrerin",
  "Leichengruft",
  "Masseur",
  "Matrose",
  "Maus",
  "Messerwerfer",
  "Mönch",
  "Morgengymnastik machen",
  "Motorrad",
  "Müllmann",
  "Muskelzucken",
  "Nagelkopf",
  "Nasenbohrer",
  "Liebling",
  "Pferd",
  "Politiker",
  "Reinigungskraft",
  "Rambo",
  "Rasenmäher",
  "Reifenpanne",
  "Reißverschluss",
  "Reiterin",
  "Rennfahrer",
  "Riese",
  "rudern",
  "Säufer",
  "Schach",
  "Schaf",
  "Schaffner",
  "Scheibenwischer",
  "Schlittschuh",
  "Schmetterlingsjäger",
  "Schornsteinfeger",
  "Schweißfüße",
  "schwimmen",
  "Schulhof",
  "Schuster",
  "abtrocknen",
  "anziehen",
  "duschen",
  "frisieren",
  "parfümieren",
  "rasieren",
  "schminken",
  "sonnen",
  "waschen",
  "wiegen",
  "Snob",
  "Sockenhalter",
  "Sonnenblume",
  "Sonnenbrand",
  "Sphinx",
  "Springmaus",
  "Spion",
  "Stammhalter",
  "Starenkasten",
  "Statue",
  "Straßenschild",
  "Strümpfe stopfen",
  "Surfer",
  "tanzen",
  "Taube",
  "Tänzerin",
  "telefonieren",
  "Testesser",
  "Tiger",
  "Tischtennis",
  "Vogel",
  "Volleyball",
  "Wagenheber",
  "wandern",
  "Wandervogel",
  "Waschmaschine",
  "Wecker",
  "Wrestler",
  "Zähne putzen",
  "Zahnpasta",
  "Zitronenfalter",
  "Zugbrücke",
  "Zwerg"
];
export default GUESS_WORDS;
