name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: yarn install

    - name: Build frontend
      run: |
        cd packages/app
        yarn build

    - name: Build server
      run: |
        cd packages/server
        yarn build

    - name: Deploy frontend
      run: |
        rm -rf /var/www/sketch.marvindv.dev/html
        mkdir /var/www/sketch.marvindv.dev/html
        mv ./packages/app/dist/* /var/www/sketch.marvindv.dev/html

    - name: Deploy server
      run: |
        rm -rf /home/github-runner/group-sketch
        mkdir /home/github-runner/group-sketch
        mv ./* /home/github-runner/group-sketch

    - name: Restart server
      run: sudo systemctl restart group-sketch-server.service
